# Generated by Django 5.1.1 on 2024-11-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Manager', 'Manager')], max_length=100),
        ),
    ]
